### PR TITLE
Remove obsolete checks from Github Actions

### PR DESCRIPTION
**Pull request by jbygdell**
* Removes all tests related to the `sda-pipeline` folder
* Remove building and publishing container form `sda-pipeline` folder
* Remove dependabot checks for `sda-pipeline` and the removed `sda-common` and `sda-s3proxy` folders
* Add `groups` to dependabot config in order to get a single PR for each folder, rather than one PR for each library update

### CODE REVIEW

**Review by blankdots — COMMENTED** [review]
if we can integrate a typo fix I made for `intercept.md` line 49 `commnly` should be `commonly` i would be happy, but it is not required

**Review by blankdots — APPROVED** [review]

**Comment by aaperis** [comment]
Are we dropping the [common](https://github.com/neicnordic/sensitive-data-archive/tree/main/sda-pipeline/.github/integration/tests/common) integration tests? I think these are good to have.

**Comment by jbygdell** [comment]
> Are we dropping the [common](https://github.com/neicnordic/sensitive-data-archive/tree/main/sda-pipeline/.github/integration/tests/common) integration tests? I think these are good to have.

Everything in the `sda`pipeline` folder is being deprecated, the folder itself will be deleted as soon as `notify` and `orchestrate` are merged into `sda`

**Review by blankdots — APPROVED** [review]

**Comment by aaperis** [comment]
> > Are we dropping the [common](https://github.com/neicnordic/sensitive-data-archive/tree/main/sda-pipeline/.github/integration/tests/common) integration tests? I think these are good to have.
> 
> Everything in the `sda-pipeline` folder is being deprecated, the folder itself will be deleted as soon as `notify` and `orchestrate` are merged into `sda`

I was referring to the tests in `10_trigger_failures.sh` and `8_bad_messages` which I can't find in the current integration tests. But maybe I missed them?

**Comment by jbygdell** [comment]
> > > Are we dropping the [common](https://github.com/neicnordic/sensitive-data-archive/tree/main/sda-pipeline/.github/integration/tests/common) integration tests? I think these are good to have.
> > 
> > 
> > Everything in the `sda-pipeline` folder is being deprecated, the folder itself will be deleted as soon as `notify` and `orchestrate` are merged into `sda`
> 
> I was referring to the tests in `10_trigger_failures.sh` and `8_bad_messages` which I can't find in the current integration tests. Do we want to keep them? Maybe we already have them somewhere but I missed them?

Should we add these tests for the `sda` folder, probably, but not as part of this PR.

**Review by aaperis — APPROVED** [review]

**Pull request merged**
