### PR TITLE
Merge all SDA related repositories

### PR DESCRIPTION
**Pull request by jbygdell**
# Merged repositories

* sda-auth
* sda-common
* sda-db
* sda-doa
* sda-download
* sda-helm
* sda-inbox-sftp
* sda-mq
* sda-pipeline
* sda-s3proxy

### CODE REVIEW

**Comment by viklund** [comment]
👿

**Review by sstli — APPROVED** [review]
OK

**Review by blankdots — COMMENTED** [review]
i see multiple golang versions, is the aim to merge first and standardize later ?

**Comment by jbygdell** [comment]
> i see multiple golang versions, is the aim to merge first and standardize later ?

Yes, step one is to get everything together first.

**Review by blankdots — DISMISSED** [review]
:rocket:

**Review by teemukataja — APPROVED** [review]
**+67,903**

**Comment by jbygdell** [comment]
@kjellp any comments from your side on this?

**Comment by kjellp** [comment]
Wow! Things are moving fast when you are away on holiday;)

Will there be integration tests available in this new repo before we make this the authorative repo, and stop maintaining the old repos? Timeline?. If so then this is just an initial PR and more are to come before the switch will happen?  Or is this the only planned PR merge before a switch should happen?

**Comment by kjellp** [comment]
Thanks @jbygdell, sounds good that the switch/deprecation only happens after PR #3 also is completed. We foresee some work/updates in sda-doa in the coming week(s), that is needed to keep up with updated dependencies, is the plan that any change to any of the repos will be done both places manually by the developers, or will there be a systematic second re-sync later to carry over any changes in the transition phase?

**Review by blankdots — APPROVED** [review]

**Review by norling — APPROVED** [review]

**Review by kjellp — APPROVED** [review]

**Pull request merged**
